apiVersion: v1
kind: Namespace
metadata:
  name: mrnwaiwu-apps
  labels:
    environment: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
  annotations:
    description: "Production workloads — restricted PSA, all Gatekeeper policies enforced"
